SION_18/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import regis_organisasi.urls as regis_organisasi
import login.urls as login
import profil_organisasi.urls as profil_organisasi
import regis_user.urls as regis_user
import kegiatan.urls as kegiatan
import profil_pribadi.urls as profil_pribadi


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^regis_organisasi/', include(regis_organisasi,namespace='regis_organisasi')),
    url(r'^login/', include(login,namespace='login')),
    url(r'^$',RedirectView.as_view(url='login/',permanent=True), name='index'),
    url(r'^profil_organisasi/', include(profil_organisasi,namespace='profil_organisasi')),
    url(r'^regis_user/', include(regis_user,namespace='regis_user')),
    url(r'^kegiatan/',include(kegiatan,namespace='kegiatan')),
    url(r'^profil_pribadi/',include(profil_pribadi,namespace='profil_pribadi')),
]

login/urls.py
from django.conf.urls import url
from .views import index
from .custom_auth import auth_login, auth_logout

#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),
]

profil_organisasi/urls.py
from django.conf.urls import url
from .views import index, add_session_organisasi,form_donasi_organisasi, donasi, jumlah_dana
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_session_organisasi',add_session_organisasi,name='add_session_organisasi'),
    url(r'^form_donasi',form_donasi_organisasi,name='form_donasi_organisasi'),
    url(r'^donasi',donasi,name='donasi'),
    url(r'^jumlah_dana',jumlah_dana,name='jumlah_dana'),
]

profil_organisasi/models.py
from django.db import models

# Create your models here.

profil_organisasi/views.py
from django.shortcuts import render
from django.db import connection
from django.http import HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
import psycopg2
import json
import datetime

# Create your views here.
response={}

def index(request):
	cursor = connection.cursor()
	cursor.execute("SET SEARCH_PATH TO SION;")
	query = "select email_organisasi,website, nama, provinsi,kabupaten_kota, kecamatan,kelurahan,kode_pos from organisasi"
	cursor.execute(query)
	result = cursor.fetchall()
	response['organisasi'] = result
	if 'organisasi' in request.session.keys():
		response['det_organisasi'] = request.session['organisasi']
	# jika tidak ditambahkan else, cache akan tetap menyimpan data
	# sebelumnya yang ada pada response, sehingga data tidak up-to-date
	else:
		response['det_organisasi'] = []

	return render(request, 'profil_organisasi.html', response)

def add_session_organisasi(request, id):
    ssn_key = request.session.keys()
    if not 'organisasi' in ssn_key:
        request.session['organisasi'] = [id]
    else:
        organisasi = request.session['organisasi']
        if id not in organisasi:
            organisasi.append(id)
            request.session['organisasi'] = organisasi

    return HttpResponseRedirect(reverse('profil_organisasi:organisasi_detail'))
def organisasi_detail(request):
	organisasi = request.session['organisasi']
	response['detail'] = organisasi
	# cursor = connection.cursor()
	# query = "select * from organisasi "
	# cursor.execute(query)
	# result1 = cursor.fetchall()
	# response['tentang'] = result1


	# query = "select * from pengurus_organisasi PO, user u where"
	# cursor.execute(query)
	# result2 = cursor.fetchall()
	# response['pengurus'] = result2


	# query = "select * from donatur_organisasi DI, donatur D, user U"
	# cursor.execute(query)
	# result3 = cursor.fetchall()
	# response['donatur'] = result3


	# query = "select * from sponsor_organisasi SO, sponsor S, user U"
	# cursor.execute(query)
	# result4 = cursor.fetchall()
	# response['sponsor'] = result4

	# query = "select * from organisasi O, tujuan_organisasi TO"
	# cursor.execute(query)
	# result5 = cursor.fetchall()
	# response['tujuan'] = result5

	return render(request,'organisasi_detail.html',response)

def form_donasi_organisasi(request):
	# cursor = connection.cursor()
	# query = "select * from organisasi"
	# cursor.execute(query)
	# result = cursor.fetchall()
	# response['donasi'] = result
	return render(request,'form_donasi.html')

@csrf_exempt
def donasi(request):
	print("mask form")
	organs = request.POST['organisasi']
	jumlah_dana = request.POST['jumlah-dana']
	time = datetime.datetime.now()
	time_real = '{:%Y-%m-%d %H:%M:%S}'.format(time)

	if request.method=='POST' :
		cursor = connection.cursor()
		cursor.execute("SET search_path to SION")
		cursor.execute("INSERT INTO  donatur_organisasi(donatur,organisasi,tanggal,nominal) VALUES (%s,%s,%s,%s)",[organs,time_real,jumlah_dana])
		cursor.execute("UPDATE donatur SET saldo= '"+jumlah_dana+"'")
		return HttpResponseRedirect("/form_donasi")

	if request.method=='POST' :
		cursor = connection.cursor()
		cursor.execute("SET search_path to SION")
		cursor.execute("INSERT INTO  sponsor_organisasi(sponsor,organisasi,tanggal,nominal) VALUES (%s,%s,%s,%s)",[organs,time_real,jumlah_dana])
		return HttpResponseRedirect("/form_donasi")

@csrf_exempt
def jumlah_dana(request):
	if request.method=='POST':
		jumlah = request.POST[jumlah_dana]
		if jumlah < 2000000:
				good = True
		else :
			bad = False

	data = {
		'is_good': good
	}
	return JsonResponse(data)

profil_organisasi/templates/form_donasi.html
{% extends "layout/profil-base.html" %}
{% block content %}

<div align="center" class="judul">
    <h1> Form Donasi </h1>
</div>
<hr>
<div align="center" class="row" id="form">
    <div class="col-md-6 col-md-offset-3">
        <div style="margin-top: 50px;" class="rata-tengah">
            <form method="POST" action="{% url 'profil_organisasi:donasi' %}">
            {% csrf_token %}
                <label for="organisasi">Organisasi</label><br>
                <select class="my-select">
                {% for don in donasi%}
                    <option>{{don.nama}}</option>
                {% endfor %}
                </select>

                <label for="jumlah-dana">Jumlah Dana</label> 
                <p style="margin-bottom: 20px;">
                    <input type="number" id="dana" name="dana" required placeholder="Jumlah Dana">
                </p>
                <input type="submit" class="btn btn-primary" value="Submit">
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block javascript %}
<script type="text/javascript">
    $(".jumlah-dana").change(function () {
        console.print('haha');
        console.log( $(this).val() );
        jumlah_dana = $(this).val();
        $.ajax({
            method: "POST",
            url: '{% url "profil_organisasi:jumlah_dana" %}',
            data: {
                'jumlah-dana': jumlah_dana
            },
            dataType: 'json',
            success: function (data) {
                console.log(data)
                if (data.is_good) {
                    alert("Jumlah dana kurang");
                }
            }
        });
    });
</script>
{% endblock %}

profil_organisasi/templates/organisasi_detail.html
{% extends "layout/profil-base.html" %}
{% block content %}
<style>
    .center_screen {
        position: absolute;
        width: 500px;
        height: 50px;
		font-size : 40px;
        top: 50%;
        left: 50%;
        margin-left: -250px; /* margin is -0.5 * dimension */
        margin-top: -25px;
		color : #040F0F;

    }
    
</style>
    <div align="center" class="nama-organisasi-detail">
        <h1>{{ detail.nama }}</h1>
    </div>    

    <div class="prof2">
         <h3 align="center" id="tentang">Tentang</h3>
        <div align="center" class="row">
             <div class="col-md-6">Jalan/Desa/Kelurahan/No.Rumah</div>
            <div class="col-md-6">{{ detail.kelurahan }}</div>
            <div class="col-md-6">Kecamatan</div>
            <div class="col-md-6">{{ detail.kecamatan }}</div>
            <div class="col-md-6">Kabupaten</div>
            <div class="col-md-6">{{ detail.kabupaten }}</div>
            <div class="col-md-6">Provinsi</div>
            <div class="col-md-6">Jakarta</div>
            <div class="col-md-6">Kode Pos</div>
            <div class="col-md-6">150589</div>
            <div class="col-md-6">Email</div>
            <div class="col-md-6">indonesia@co</div>
            <div class="col-md-6">Website</div>
            <div class="col-md-6">indonesia.co</div>
            <div class="col-md-6">Tujuan Organisasi</div>
            <div class="col-md-6">membangun semangat</div>
        </div>
        <h3 align="center" id="pengurus">Pengurus Organisasi</h3>
        <div class="pengurus-organisasi">
            <div class="data-pengurus-organisasi">
                <table align="center" class="data-pengurus">
               
                    <tr><td>Sudirman</td></tr> 
                
                </table>
            </div>
        </div>
        <div align="center" class="row" id="donatur-sponsor">
             <div class="col-md-4">
                 <div >
                </div>
             </div>
             <div class="col-md-4">
                 <div id="donatur">
                    <h3>Donatur</h3>
                 </div>
             </div>
            <div class="col-md-4">
                <div>
                </div>
            </div>
        </div>
        <div align="center" class="row">
        
            <div class="col-md-4"></div>
            <div class="col-md-4">Yeni</div>
            <div class="col-md-4"></div>
        
        </div>

        <div align="center" class="row" id="donatur-sponsor">
             <div class="col-md-4">
                 <div>
                </div>
             </div>
             <div class="col-md-4">
                 <div id="sponsor">
                    <h3>Sponsor</h3>
                </div>
             </div>
            <div class="col-md-4">
                <div>
                </div>
            </div>
        </div>
        <div align="center" class="row">
        
            <div class="col-md-4"></div>
            <div class="col-md-4">Laurel</div>
            <div class="col-md-4"></div>
        
        </div>


{% endblock %}

profil_organisasi/templates/profil_organisasi.html
{% extends "layout/profil-base.html" %}
{% block content %}
<style>
    .center_screen {
        position: absolute;
        width: 400px;
        height: 50px;
		font-size : 40px;
        top: 50%;
        left: 50%;
        margin-left: -250px; /* margin is -0.5 * dimension */
        margin-top: -25px;
		color : #040F0F;
    }
        
</style>
<div align="center" class="home-organisasi">
    <h1>Organisasi Nirlaba</h1>
</div>    

<div class="prof2">
    <table class="table">
        <thead id="head-table">
            <th id="head-1"> No</th>
            <th id="head-2"> Nama Organisasi</th>
            <th id="head-3"> </th>
            </thead>
            
                <tbody>
                {% for row in organisasi %}
                   <tr id="row-table">
                        <td> {{forloop.counter}} </td>
                        <td> {{row.2}} </td>
                        <td id="lihat-organisasi"> 
                            <a href="{%url 'profil_organisasi:add_session_organisasi' %}">Lihat Organisasi</a>
                        </td>
                    </tr>
                    <br>
                {% endfor %}
                </tbody>
            
        </table>
    </div>
<br>
    <div style="margin-top: 50px;margin-left: 100px;">
        <a href="{%url 'profil_organisasi:form_donasi_organisasi' %}">Donasi Organisasi</a>
    </div>

{%endblock%}

{% block javascript %}
<script type="text/javascript">
    $(".jumlah-dana").change(function () {
        console.print('haha');
        console.log( $(this).val() );
        jumlah_dana = $(this).val();
        $.ajax({
            method: "POST",
            url: '{% url "profil_organisasi:jumlah_dana" %}',
            data: {
                'jumlah-dana': jumlah_dana
            },
            dataType: 'json',
            success: function (data) {
                console.log(data)
                if (data.is_good) {
                    alert("Jumlah dana kurang");
                }
            }
        });
    });
</script>
{% endblock %}